services:
  - type: web
    name: frameworkvoter
    env: node
    plan: starter
    buildCommand: yarn; yarn blitz db migrate; yarn blitz build
    startCommand: yarn blitz start --production -H 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: frameworkvoter-db
          property: connectionString
databases:
  - name: frameworkvoter-db
    plan: starter
