services:
  - type: web
    name: frameworkvoter
    env: node
    plan: starter
    buildCommand: yarn; blitz db migrate; blitz build
    startCommand: blitz start --production -H 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: frameworkvoter-db
          property: connectionString
databases:
  - name: frameworkvoter-db
    plan: starter
